const DASHBOARD_MAIN_PANEL_SOURCE = [
  "function normalizeMainTab(tab) {",
  "  if (tab === 'skills' || tab === 'config' || tab === 'home') return tab;",
  "  if (tab === 'overview' || tab === 'activity' || tab === 'cost' || tab === 'logs') return 'home';",
  "  return 'home';",
  "}",
  "",
  "function renderWorkspaceTabs() {",
  "  const el = document.getElementById('workspaceTabs');",
  "  if (!el) return;",
  "  const activeTab = normalizeMainTab(state.selectedMainTab);",
  "  if (state.selectedMainTab !== activeTab) {",
  "    state.selectedMainTab = activeTab;",
  "  }",
  "  el.innerHTML = '<div class=\"main-tabs\">' +",
  "    '<button class=\"main-tab ' + (activeTab === 'home' ? 'active' : '') + '\" onclick=\"selectMainTab(\\'home\\')\">' + t('mainTabHome') + '</button>' +",
  "    '<button class=\"main-tab ' + (activeTab === 'skills' ? 'active' : '') + '\" onclick=\"selectMainTab(\\'skills\\')\">' + t('mainTabSkills') + '</button>' +",
  "    '<button class=\"main-tab ' + (activeTab === 'config' ? 'active' : '') + '\" onclick=\"selectMainTab(\\'config\\')\">' + t('mainTabConfig') + '</button>' +",
  "  '</div>';",
  "}",
  "",
  "function renderHomePage(projectPath, input) {",
  "  const overviewHtml = renderDashboardOverviewPanel({",
  "    agentUsage: input.agentUsage,",
  "    daemon: input.daemon,",
  "    decisionSummary: input.decisionSummary,",
  "    deps: {",
  "      escHtml,",
  "      formatUptime,",
  "      formatUsageCompact,",
  "      renderMetricRows,",
  "      renderStateBadge,",
  "      renderTraceBars,",
  "      t,",
  "      timeAgo,",
  "    },",
  "    hasDecisionEvents: input.decisionEvents.length > 0,",
  "    skillsCount: input.skills.length,",
  "    traceStats: input.traceStats,",
  "  });",
  "",
  "  const activityHtml = renderDashboardActivityPanel({",
  "    activityLayer: state.activityLayer,",
  "    deps: {",
  "      renderBusinessEvents,",
  "      renderRecentTraces,",
  "      renderTraceBars,",
  "      t,",
  "    },",
  "    projectPath,",
  "    recentTraces: input.recentTraces,",
  "    traceStats: input.traceStats,",
  "  });",
  "",
  "  const costHtml = '<div class=\"card\">' +",
  "    '<div class=\"card-header\"><span>' + t('mainTabCost') + '</span><span style=\"color:var(--muted)\">' + (input.agentUsage.callCount ?? 0) + '</span></div>' +",
  "    '<div class=\"card-body\">' + renderCostPanel(projectPath) + '</div>' +",
  "  '</div>';",
  "",
  "  const logsHtml = renderDashboardLogsPanel({ deps: { t }, logFilter: state.logFilter });",
  "",
  "  return '<div class=\"page-shell\">' +",
  "    '<div class=\"page-hero\">' +",
  "      '<div>' +",
  "        '<div class=\"page-kicker\">OrnnSkills</div>' +",
  "        '<div class=\"page-title\">' + t('mainTabHome') + '</div>' +",
  "        '<div class=\"page-copy\">' + t('mainTabOverview') + ' · ' + t('traceTitle') + ' · ' + t('mainTabCost') + ' · ' + t('mainTabLogs') + '</div>' +",
  "      '</div>' +",
  "      '<div class=\"page-meta\">' + t('statShadowSkills') + ': ' + input.skills.length + '</div>' +",
  "    '</div>' +",
  "    renderProviderAlert(projectPath) +",
  "    overviewHtml +",
  "    '<div class=\"home-grid\">' +",
  "      '<div class=\"home-primary\">' + activityHtml + '</div>' +",
  "      '<div class=\"home-secondary\">' + costHtml + logsHtml + '</div>' +",
  "    '</div>' +",
  "  '</div>';",
  "}",
  "",
  "function renderSkillsPage(projectPath, input) {",
  "  return '<div class=\"page-shell\">' +",
  "    '<div class=\"page-hero\">' +",
  "      '<div>' +",
  "        '<div class=\"page-kicker\">OrnnSkills</div>' +",
  "        '<div class=\"page-title\">' + t('mainTabSkills') + '</div>' +",
  "        '<div class=\"page-copy\">' + t('skillsTitle') + ' · ' + t('skillsCount') + '</div>' +",
  "      '</div>' +",
  "      '<div class=\"page-meta\">' + t('skillsCount') + ': ' + input.filteredSkills.length + '</div>' +",
  "    '</div>' +",
  "    renderDashboardSkillsPanel({",
  "      deps: {",
  "        renderSkillCard,",
  "        renderSkillsEmptyState,",
  "        t,",
  "      },",
  "      filteredSkills: input.filteredSkills,",
  "      projectPath,",
  "      searchQuery: state.searchQuery,",
  "      selectedRuntimeTab: state.selectedRuntimeTab,",
  "      sortBy: state.sortBy,",
  "      sortOrder: state.sortOrder,",
  "    }) +",
  "  '</div>';",
  "}",
  "",
  "function renderConfigPage(projectPath) {",
  "  return '<div class=\"page-shell\">' +",
  "    '<div class=\"page-hero\">' +",
  "      '<div>' +",
  "        '<div class=\"page-kicker\">OrnnSkills</div>' +",
  "        '<div class=\"page-title\">' + t('mainTabConfig') + '</div>' +",
  "        '<div class=\"page-copy\">' + t('configIntro') + '</div>' +",
  "      '</div>' +",
  "      '<div class=\"page-meta\">' + t('configTitle') + '</div>' +",
  "    '</div>' +",
  "    renderProviderAlert(projectPath) +",
  "    '<div class=\"card\">' +",
  "      '<div class=\"card-header\"><span>' + t('configTitle') + '</span></div>' +",
  "      '<div class=\"card-body\">' + renderConfigPanel(projectPath) + '</div>' +",
  "    '</div>' +",
  "  '</div>';",
  "}",
  "",
  "function renderMainPanel(projectPath) {",
  "  const active = document.activeElement;",
  "  const shouldRestoreSearchFocus = active && active.id === 'skillSearchInput';",
  "  const prevSearchSelectionStart = shouldRestoreSearchFocus ? active.selectionStart : null;",
  "  const prevSearchSelectionEnd = shouldRestoreSearchFocus ? active.selectionEnd : null;",
  "",
  "  renderWorkspaceTabs();",
  "",
  "  const el = document.getElementById('mainPanel');",
  "  const pd = state.projectData[projectPath];",
  "  if (!pd) { el.innerHTML = '<div class=\"panel-inner\"><div class=\"no-project\">' + t('mainNoData') + '</div></div>'; return; }",
  "",
  "  const normalizedTab = normalizeMainTab(state.selectedMainTab);",
  "  if (state.selectedMainTab !== normalizedTab) {",
  "    state.selectedMainTab = normalizedTab;",
  "    renderWorkspaceTabs();",
  "  }",
  "",
  "  const daemon = pd.daemon || { isRunning: false, processedTraces: 0, optimizationStatus: { queueSize: 0 }, retryQueueSize: 0 };",
  "  const skills = pd.skills || [];",
  "  const traceStats = pd.traceStats || { total: 0, byRuntime: {}, byStatus: {}, byEventType: {} };",
  "  const recentTraces = pd.recentTraces || [];",
  "  const decisionEvents = pd.decisionEvents || [];",
  "  const decisionSummary = summarizeDecisionEvents(decisionEvents);",
  "  const filteredSkills = getFilteredAndSortedSkills(skills);",
  "  const agentUsage = pd.agentUsage || {",
  "    callCount: 0,",
  "    promptTokens: 0,",
  "    completionTokens: 0,",
  "    totalTokens: 0,",
  "    durationMsTotal: 0,",
  "    avgDurationMs: 0,",
  "    lastCallAt: null,",
  "    byModel: {},",
  "    byScope: {},",
  "    bySkill: {},",
  "  };",
  "",
  "  let contentHtml = '';",
  "  if (normalizedTab === 'home') {",
  "    contentHtml = renderHomePage(projectPath, {",
  "      agentUsage,",
  "      daemon,",
  "      decisionEvents,",
  "      decisionSummary,",
  "      recentTraces,",
  "      skills,",
  "      traceStats,",
  "    });",
  "  } else if (normalizedTab === 'skills') {",
  "    contentHtml = renderSkillsPage(projectPath, { filteredSkills });",
  "  } else if (normalizedTab === 'config') {",
  "    contentHtml = renderConfigPage(projectPath);",
  "  }",
  "",
  "  el.innerHTML = '<div class=\"panel-inner\">' + contentHtml + '</div>';",
  "",
  "  if (shouldRestoreSearchFocus) {",
  "    const nextInput = document.getElementById('skillSearchInput');",
  "    if (nextInput) {",
  "      nextInput.focus();",
  "      if (prevSearchSelectionStart !== null && prevSearchSelectionEnd !== null) {",
  "        nextInput.setSelectionRange(prevSearchSelectionStart, prevSearchSelectionEnd);",
  "      }",
  "    }",
  "  }",
  "",
  "  if (normalizedTab === 'home') {",
  "    renderLogs();",
  "  }",
  "  if (normalizedTab === 'config') {",
  "    ensureConfigTabDependencies(projectPath);",
  "    void ensureProjectConfig(projectPath);",
  "  }",
  "}",
  "",
  "function showProjectRenderFailure(projectPath, source, error) {",
  "  renderWorkspaceTabs();",
  "  const el = document.getElementById('mainPanel');",
  "  if (!el) return;",
  "  el.innerHTML =",
  "    '<div class=\"panel-inner\"><div class=\"card\"><div class=\"card-header\"><span>' +",
  "    escHtml(t('mainSelectProject')) +",
  "    '</span></div><div class=\"card-body\"><div class=\"empty-state\" style=\"color:var(--yellow)\">' +",
  "    escHtml(t('projectRenderFailed')) +",
  "    '</div><div class=\"config-help\" style=\"margin-top:8px\">' +",
  "    escHtml(t('projectRenderHint')) +",
  "    '</div><div class=\"config-help\" style=\"margin-top:8px\">' +",
  "    escHtml(projectPath || '—') +",
  "    (source ? ' · ' + escHtml(source) : '') +",
  "    '</div></div></div></div>';",
  "  console.error('[dashboard] main panel render failed', {",
  "    projectPath,",
  "    source,",
  "    error: String(error),",
  "  });",
  "  enqueueClientError({",
  "    message: 'main panel render failed: ' + String(error),",
  "    source: source || 'renderMainPanel',",
  "    stack: getErrorStack(error),",
  "  });",
  "}",
  "",
  "function safeRenderMainPanel(projectPath, source = 'renderMainPanel') {",
  "  try {",
  "    renderMainPanel(projectPath);",
  "    return true;",
  "  } catch (error) {",
  "    showProjectRenderFailure(projectPath, source, error);",
  "    return false;",
  "  }",
  "}",
  "",
  "function selectMainTab(tab) {",
  "  const normalizedTab = normalizeMainTab(tab);",
  "  state.selectedMainTab = normalizedTab;",
  "  renderWorkspaceTabs();",
  "  if ((normalizedTab === 'config' || normalizedTab === 'home') && state.providerCatalog.length === 0) {",
  "    void loadProviderCatalog(true);",
  "  }",
  "  if (normalizedTab === 'config' && state.selectedProjectId) {",
  "    ensureConfigTabDependencies(state.selectedProjectId);",
  "  }",
  "  if (normalizedTab !== 'config' && state.selectedProjectId && state.staleProjectData[state.selectedProjectId]) {",
  "    void loadProjectSnapshot(state.selectedProjectId, { force: true }).then(() => {",
  "      if (state.selectedProjectId) {",
  "        safeRenderMainPanel(state.selectedProjectId, 'selectMainTab:refresh:' + normalizedTab);",
  "      }",
  "    });",
  "  }",
  "  if (state.selectedProjectId) {",
  "    safeRenderMainPanel(state.selectedProjectId, 'selectMainTab:' + normalizedTab);",
  "  }",
  "  console.debug('[dashboard] switched main tab', { tab: normalizedTab, requestedTab: tab });",
  "}",
  "",
  "const baseFetchJsonWithTimeout = fetchJsonWithTimeout;",
  "fetchJsonWithTimeout = async function(url, timeoutMs = 8000, options = {}) {",
  "  const data = await baseFetchJsonWithTimeout(url, timeoutMs, options);",
  "  if (String(url) === '/api/logs') {",
  "    state.allLogs = Array.isArray(data?.lines) ? data.lines : [];",
  "    if (normalizeMainTab(state.selectedMainTab) === 'home') {",
  "      renderLogs();",
  "    }",
  "  }",
  "  return data;",
  "};",
  "",
  "const baseSwitchLang = switchLang;",
  "switchLang = async function(lang) {",
  "  await baseSwitchLang(lang);",
  "  renderWorkspaceTabs();",
  "};",
  "",
  "const baseHandleUpdate = handleUpdate;",
  "handleUpdate = async function(data) {",
  "  await baseHandleUpdate(data);",
  "  renderWorkspaceTabs();",
  "  if (data?.logs && normalizeMainTab(state.selectedMainTab) === 'home') {",
  "    renderLogs();",
  "  }",
  "};",
  "",
  "const baseLoadProviderCatalog = loadProviderCatalog;",
  "loadProviderCatalog = async function(force = false) {",
  "  const activeProjectId = state.selectedProjectId;",
  "  const activeTab = normalizeMainTab(state.selectedMainTab);",
  "  await baseLoadProviderCatalog(force);",
  "  if (activeProjectId && activeProjectId === state.selectedProjectId && (activeTab === 'home' || activeTab === 'config')) {",
  "    safeRenderMainPanel(activeProjectId, 'loadProviderCatalog:' + activeTab);",
  "  }",
  "};",
  "",
  "const baseInit = init;",
  "init = async function() {",
  "  renderWorkspaceTabs();",
  "  await baseInit();",
  "  renderWorkspaceTabs();",
  "  if (!state.selectedProjectId) {",
  "    const mainPanelEl = document.getElementById('mainPanel');",
  "    if (mainPanelEl && !mainPanelEl.innerHTML.trim()) {",
  "      mainPanelEl.innerHTML = '<div class=\"panel-inner\"><div class=\"no-project\">' + t('sidebarNoProjects') + '</div></div>';",
  "    }",
  "  }",
  "};",
  "",
  "function setActivityLayer(layer) {",
  "  state.activityLayer = layer === 'raw' ? 'raw' : 'business';",
  "  if (state.selectedProjectId) safeRenderMainPanel(state.selectedProjectId, 'setActivityLayer');",
  "}",
  "",
  "function setActivityTagFilter(tag) {",
  "  state.activityTagFilter = tag || 'core_flow';",
  "  if (state.selectedProjectId) safeRenderMainPanel(state.selectedProjectId, 'setActivityTagFilter');",
  "}",
].join('\n');

export function renderDashboardMainPanelSource(): string {
  return DASHBOARD_MAIN_PANEL_SOURCE;
}
