const DASHBOARD_MAIN_PANEL_SOURCE = [
  "function isLegacyProjectMainTab(tab) {\n  return tab === 'overview' || tab === 'activity' || tab === 'cost' || tab === 'logs';\n}",
  "function normalizeMainTab(tab) {",
  "  if (tab === 'skills' || tab === 'project' || tab === 'config') return tab;",
  "  if (tab === 'home' || isLegacyProjectMainTab(tab)) return 'project';",
  "  return 'skills';",
  "}",
  "function normalizeSkillsSubTab(tab) {",
  "  return tab === 'skill_library' ? 'skill_library' : 'skill_library';",
  "}",
  "function syncWorkspaceState(rawMainTab) {",
  "  const requestedMainTab = typeof rawMainTab === 'string' && rawMainTab ? rawMainTab : state.selectedMainTab;",
  "  const normalizedMainTab = normalizeMainTab(requestedMainTab);",
  "  if (state.selectedMainTab !== normalizedMainTab) {",
  "    state.selectedMainTab = normalizedMainTab;",
  "  }",
  "  state.selectedSkillsSubTab = normalizeSkillsSubTab(state.selectedSkillsSubTab);",
  "  return {",
  "    mainTab: normalizedMainTab,",
  "    skillsSubTab: state.selectedSkillsSubTab,",
  "  };",
  "}",
  "function needsProjectOverviewDependencies(mainTab = state.selectedMainTab) {",
  "  const normalizedMainTab = normalizeMainTab(mainTab);",
  "  return normalizedMainTab === 'project' || normalizedMainTab === 'config';",
  "}",
  "function syncWorkspaceLayout() {",
  "  const showProjectNavigation = normalizeMainTab(state.selectedMainTab) === 'project';",
  "  const mainEl = document.getElementById('workspaceMain');",
  "  const sidebarEl = document.getElementById('projectSidebar');",
  "  if (mainEl) {",
  "    mainEl.classList.toggle('project-nav-visible', showProjectNavigation);",
  "  }",
  "  if (sidebarEl) {",
  "    sidebarEl.style.display = showProjectNavigation ? 'flex' : 'none';",
  "  }",
  "}",
  "function renderWorkspaceTabs() {",
  "  const el = document.getElementById('workspaceTabs');",
  "  if (!el) return;",
  "  const workspaceState = syncWorkspaceState();",
  "  syncWorkspaceLayout();",
  "  el.innerHTML = '<div class=\"main-tabs\">' +",
  "    '<button class=\"main-tab ' + (workspaceState.mainTab === 'skills' ? 'active' : '') + '\" onclick=\"selectMainTab(\\'skills\\')\">' + t('mainTabSkills') + '</button>' +",
  "    '<button class=\"main-tab ' + (workspaceState.mainTab === 'project' ? 'active' : '') + '\" onclick=\"selectMainTab(\\'project\\')\">' + t('mainTabProject') + '</button>' +",
  "    '<button class=\"main-tab ' + (workspaceState.mainTab === 'config' ? 'active' : '') + '\" onclick=\"selectMainTab(\\'config\\')\">' + t('mainTabConfig') + '</button>' +",
  "  '</div>';",
  "}",
  "function findProjectByPath(projectPath) {",
  "  return (Array.isArray(state.projects) ? state.projects : []).find(function(project) {",
  "    return project && project.path === projectPath;",
  "  }) || null;",
  "}",
  "function getProjectSkillCount(projectPath, snapshot) {",
  "  if (snapshot && Array.isArray(snapshot.skills)) {",
  "    return snapshot.skills.length;",
  "  }",
  "  const project = findProjectByPath(projectPath);",
  "  return Number(project && project.skillCount) || 0;",
  "}",
  "function buildGlobalHomeSummary() {",
  "  const projects = Array.isArray(state.projects) ? state.projects : [];",
  "  const rows = projects.map(function(project) {",
  "    const snapshot = state.projectData[project.path] || null;",
  "    const paused = typeof isProjectMonitoringPaused === 'function'",
  "      ? isProjectMonitoringPaused(project, snapshot)",
  "      : (project && (project.isPaused === true || project.monitoringState === 'paused'));",
  "    const running = snapshot && snapshot.daemon && typeof snapshot.daemon.isRunning === 'boolean'",
  "      ? snapshot.daemon.isRunning",
  "      : project && typeof project.isRunning === 'boolean'",
  "        ? project.isRunning",
  "        : null;",
  "    const skillCount = getProjectSkillCount(project.path, snapshot);",
  "    const traceCount = Number(snapshot && snapshot.traceStats && snapshot.traceStats.total) || 0;",
  "    const agentCalls = Number(snapshot && snapshot.agentUsage && snapshot.agentUsage.callCount) || 0;",
  "    return {",
  "      path: project.path,",
  "      name: project.name || project.path,",
  "      paused: !!paused,",
  "      running: running,",
  "      skillCount: skillCount,",
  "      traceCount: traceCount,",
  "      agentCalls: agentCalls,",
  "    };",
  "  });",
  "  return {",
  "    projectsCount: rows.length,",
  "    monitoredProjects: rows.filter(function(row) { return !row.paused; }).length,",
  "    totalSkills: rows.reduce(function(sum, row) { return sum + row.skillCount; }, 0),",
  "    totalCalls: rows.reduce(function(sum, row) { return sum + row.agentCalls; }, 0),",
  "    rows: rows,",
  "  };",
  "}",
  "function renderSummaryStatCard(label, value, subtext) {",
  "  return '<div class=\"stat-card\">' +",
  "    '<div class=\"stat-label\">' + escHtml(label) + '</div>' +",
  "    '<div class=\"stat-value\">' + escHtml(formatUsageCompact(value)) + '</div>' +",
  "    (subtext ? '<div class=\"stat-sub\">' + escHtml(subtext) + '</div>' : '') +",
  "  '</div>';",
  "}",
  "function renderGlobalProjectRows(rows) {",
  "  if (!rows.length) {",
  "    return '<div class=\"empty-state\">' + t('homeGlobalProjectListEmpty') + '</div>';",
  "  }",
  "  return '<div class=\"project-summary-list\">' + rows.map(function(row) {",
  "    const statusText = row.paused",
  "      ? t('sidebarPaused')",
  "      : row.running === false",
  "        ? t('sidebarStopped')",
  "        : t('sidebarRunning');",
  "    return '<div class=\"project-summary-row\">' +",
  "      '<div class=\"project-summary-main\">' +",
  "        '<div class=\"project-summary-name\">' + escHtml(row.name) + '</div>' +",
  "        '<div class=\"project-summary-path\">' + escHtml(row.path) + '</div>' +",
  "        '<div class=\"project-summary-meta\">' +",
  "          '<span>' + escHtml(t('sidebarSkills')) + ': ' + escHtml(String(row.skillCount)) + '</span>' +",
  "          '<span>' + escHtml(t('statTraces')) + ': ' + escHtml(String(row.traceCount)) + '</span>' +",
  "          '<span>' + escHtml(t('homeGlobalCalls')) + ': ' + escHtml(formatUsageCompact(row.agentCalls)) + '</span>' +",
  "        '</div>' +",
  "      '</div>' +",
  "      '<span class=\"project-summary-badge\">' + escHtml(statusText) + '</span>' +",
  "    '</div>';",
  "  }).join('') + '</div>';",
  "}",
  "function renderGlobalHomePage() {",
  "  const summary = buildGlobalHomeSummary();",
  "  return '<div class=\"page-shell\">' +",
  "    '<div class=\"stats-row\">' +",
  "      renderSummaryStatCard(t('homeGlobalProjects'), summary.projectsCount, '') +",
  "      renderSummaryStatCard(t('homeGlobalMonitoring'), summary.monitoredProjects, '') +",
  "      renderSummaryStatCard(t('homeGlobalSkills'), summary.totalSkills, '') +",
  "      renderSummaryStatCard(t('homeGlobalCalls'), summary.totalCalls, '') +",
  "    '</div>' +",
  "    '<div class=\"card\">' +",
  "      '<div class=\"card-header\"><span>' + t('homeGlobalProjectListTitle') + '</span><span>' + summary.projectsCount + '</span></div>' +",
  "      '<div class=\"card-body\">' + renderGlobalProjectRows(summary.rows) + '</div>' +",
  "    '</div>' +",
  "  '</div>';",
  "}",
  "function renderProjectWorkbenchContent(projectPath, input) {",
  "  const workbenchHtml = renderDashboardSkillsPanel({",
  "    deps: {",
  "      renderSkillCard,",
  "      renderSkillsEmptyState,",
  "      t,",
  "    },",
  "    filteredSkills: input.filteredSkills,",
  "    projectPath,",
  "    searchQuery: state.searchQuery,",
  "    selectedRuntimeTab: 'all',",
  "    sortBy: state.sortBy,",
  "    sortOrder: state.sortOrder,",
  "  });",
  "  const overviewHtml = renderDashboardOverviewPanel({",
  "    agentUsage: input.agentUsage,",
  "    daemon: input.daemon,",
  "    decisionSummary: input.decisionSummary,",
  "    deps: {",
  "      escHtml,",
  "      formatUptime,",
  "      formatUsageCompact,",
  "      renderMetricRows,",
  "      renderStateBadge,",
  "      renderTraceBars,",
  "      t,",
  "      timeAgo,",
  "    },",
  "    hasDecisionEvents: input.decisionEvents.length > 0,",
  "    skillsCount: input.skills.length,",
  "    traceStats: input.traceStats,",
  "  });",
  "  const activityHtml = renderDashboardActivityPanel({",
  "    activityLayer: state.activityLayer,",
  "    deps: {",
  "      renderBusinessEvents,",
  "      renderRecentTraces,",
  "      renderTraceBars,",
  "      t,",
  "    },",
  "    projectPath,",
  "    recentTraces: input.recentTraces,",
  "    traceStats: input.traceStats,",
  "  });",
  "  const costHtml = '<div class=\"card\">' +",
  "    '<div class=\"card-header\"><span>' + t('mainTabCost') + '</span><span style=\"color:var(--muted)\">' + (input.agentUsage.callCount ?? 0) + '</span></div>' +",
  "    '<div class=\"card-body\">' + renderCostPanel(projectPath) + '</div>' +",
  "  '</div>';",
  "  const logsHtml = renderDashboardLogsPanel({ deps: { t }, logFilter: state.logFilter });",
  "  return renderProviderAlert(projectPath) +",
  "    workbenchHtml +",
  "    overviewHtml +",
  "    '<div class=\"home-grid\">' +",
  "      '<div class=\"home-primary\">' + activityHtml + '</div>' +",
  "      '<div class=\"home-secondary\">' + costHtml + logsHtml + '</div>' +",
  "    '</div>';",
  "}",
  "function renderSkillLibraryContent(projectPath, input) {",
  "  if (!state.skillLibraryLoaded && !state.skillLibraryLoading) {",
  "    void loadSkillLibrary(false);",
  "  }",
  "  const filteredFamilies = getFilteredAndSortedSkillFamilies();",
  "  const listHtml = renderDashboardSkillsPanel({",
  "    deps: {",
  "      renderSkillCard: renderFamilyCard,",
  "      renderSkillsEmptyState,",
  "      t,",
  "    },",
  "    filteredSkills: filteredFamilies,",
  "    listClassName: 'skill-library-nav-list',",
  "    listContainerId: 'skillLibraryNavContainer',",
  "    projectPath: projectPath || '',",
  "    searchQuery: state.searchQuery,",
  "    selectedRuntimeTab: state.selectedRuntimeTab,",
  "    sortBy: state.sortBy,",
  "    sortOrder: state.sortOrder,",
  "    variant: 'sidebar',",
  "  });",
  "  const toolbarHtml = '<div class=\"skill-library-page-toolbar\">' +",
  "    '<div class=\"skill-library-page-toolbar-secondary\">' +",
  "      '<div class=\"search-box skill-library-search-box\">' +",
  "        '<span class=\"search-icon\">🔍</span>' +",
  "        '<input type=\"text\" class=\"search-input\" id=\"skillSearchInput\" placeholder=\"' + escHtml(t('skillsSearchPlaceholder')) + '\" value=\"' + escHtml(state.searchQuery || '') + '\" oninput=\"handleSearch(this.value)\" />' +",
  "      '</div>' +",
  "      '<div class=\"sort-controls\">' +",
  "        '<span class=\"sort-label\">' + t('skillsSortLabel') + '</span>' +",
  "        '<button class=\"sort-btn ' + (state.sortBy === 'name' ? 'active' : '') + '\" onclick=\"toggleSort(\\'name\\')\">' +",
  "          t('skillsSortName') + ' <span class=\"arrow\">' + (state.sortBy === 'name' ? (state.sortOrder === 'asc' ? '↑' : '↓') : '') + '</span>' +",
  "        '</button>' +",
  "        '<button class=\"sort-btn ' + (state.sortBy === 'updated' ? 'active' : '') + '\" onclick=\"toggleSort(\\'updated\\')\">' +",
  "          t('skillsSortUpdated') + ' <span class=\"arrow\">' + (state.sortBy === 'updated' ? (state.sortOrder === 'asc' ? '↑' : '↓') : '') + '</span>' +",
  "        '</button>' +",
  "      '</div>' +",
  "    '</div>' +",
  "  '</div>';",
  "  const errorHtml = state.skillLibraryError",
  "    ? '<div class=\"card\"><div class=\"card-body\"><div class=\"empty-state\">' + escHtml(state.skillLibraryError) + '</div></div></div>'",
  "    : '';",
  "  return errorHtml + toolbarHtml + '<div class=\"skill-library-layout\">' +",
  "    '<div class=\"skill-library-sidebar\">' + listHtml + '</div>' +",
  "    '<div class=\"skill-library-detail\">' + renderSkillLibraryDetail() + '</div>' +",
  "  '</div>';",
  "}",
  "function renderSkillsWorkspace(projectPath, input) {",
  "  return '<div class=\"page-shell\">' +",
  "    renderSkillLibraryContent(projectPath, input) +",
  "  '</div>';",
  "}",
  "function renderProjectEmptyWorkspace(projectPath) {",
  "  return '<div class=\"project-shell\">' +",
  "    '<div class=\"card\"><div class=\"card-body\"><div class=\"empty-state\">' + t('mainSelectProject') + '</div></div></div>' +",
  "  '</div>';",
  "}",
  "function renderConfigPage(projectPath) {",
  "  return '<div class=\"page-shell\">' +",
  "    renderProviderAlert(projectPath) +",
  "    '<div class=\"card\">' +",
  "      '<div class=\"card-header\"><span>' + t('configTitle') + '</span></div>' +",
  "      '<div class=\"card-body\">' + renderConfigPanel(projectPath) + '</div>' +",
  "    '</div>' +",
  "  '</div>';",
  "}",
  "function renderMainPanel(projectPath) {",
  "  const active = document.activeElement;",
  "  const shouldRestoreSearchFocus = active && active.id === 'skillSearchInput';",
  "  const prevSearchSelectionStart = shouldRestoreSearchFocus ? active.selectionStart : null;",
  "  const prevSearchSelectionEnd = shouldRestoreSearchFocus ? active.selectionEnd : null;",
  "  const workspaceState = syncWorkspaceState();",
  "  const activeProjectPath = projectPath || state.selectedProjectId || '';",
  "  syncWorkspaceLayout();",
  "  renderWorkspaceTabs();",
  "  const el = document.getElementById('mainPanel');",
  "  let contentHtml = '';",
  "  const pd = activeProjectPath ? state.projectData[activeProjectPath] : null;",
  "  const daemon = pd && pd.daemon ? pd.daemon : { isRunning: false, processedTraces: 0, optimizationStatus: { queueSize: 0 }, retryQueueSize: 0 };",
  "  const skills = pd && Array.isArray(pd.skills) ? pd.skills : [];",
  "  const traceStats = pd && pd.traceStats ? pd.traceStats : { total: 0, byRuntime: {}, byStatus: {}, byEventType: {} };",
  "  const recentTraces = pd && Array.isArray(pd.recentTraces) ? pd.recentTraces : [];",
  "  const decisionEvents = pd && Array.isArray(pd.decisionEvents) ? pd.decisionEvents : [];",
  "  const decisionSummary = summarizeDecisionEvents(decisionEvents);",
  "  const filteredSkills = getFilteredAndSortedSkills(skills);",
  "  const agentUsage = pd && pd.agentUsage ? pd.agentUsage : {",
  "      callCount: 0,",
  "      promptTokens: 0,",
  "      completionTokens: 0,",
  "      totalTokens: 0,",
  "      durationMsTotal: 0,",
  "      avgDurationMs: 0,",
  "      lastCallAt: null,",
  "      byModel: {},",
  "      byScope: {},",
  "      bySkill: {},",
  "    };",
  "  if (workspaceState.mainTab === 'skills') {",
  "    contentHtml = renderSkillsWorkspace(activeProjectPath, {",
  "      agentUsage: agentUsage,",
  "      daemon: daemon,",
  "      decisionEvents: decisionEvents,",
  "      decisionSummary: decisionSummary,",
  "      filteredSkills: filteredSkills,",
  "      recentTraces: recentTraces,",
  "      skills: skills,",
  "      traceStats: traceStats,",
  "    });",
  "  } else if (workspaceState.mainTab === 'project') {",
  "    if (!activeProjectPath || !pd) {",
  "      contentHtml = renderProjectEmptyWorkspace(activeProjectPath);",
  "    } else {",
  "      contentHtml = '<div class=\"project-shell\">' + renderProjectWorkbenchContent(activeProjectPath, {",
  "        agentUsage: agentUsage,",
  "        daemon: daemon,",
  "        decisionEvents: decisionEvents,",
  "        decisionSummary: decisionSummary,",
  "        filteredSkills: filteredSkills,",
  "        recentTraces: recentTraces,",
  "        skills: skills,",
  "        traceStats: traceStats,",
  "      }) + '</div>';",
  "    }",
  "  } else if (workspaceState.mainTab === 'config') {",
  "    if (!activeProjectPath) {",
  "      contentHtml = '<div class=\"page-shell\"><div class=\"card\"><div class=\"card-body\"><div class=\"empty-state\">' + t('mainSelectProject') + '</div></div></div></div>';",
  "    } else {",
  "      contentHtml = renderConfigPage(activeProjectPath);",
  "    }",
  "  }",
  "  el.innerHTML = '<div class=\"panel-inner\">' + contentHtml + '</div>';",
  "  if (shouldRestoreSearchFocus) {",
  "    const nextInput = document.getElementById('skillSearchInput');",
  "    if (nextInput) {",
  "      nextInput.focus();",
  "      if (prevSearchSelectionStart !== null && prevSearchSelectionEnd !== null) {",
  "        nextInput.setSelectionRange(prevSearchSelectionStart, prevSearchSelectionEnd);",
  "      }",
  "    }",
  "  }",
  "  if (workspaceState.mainTab === 'project') {",
  "    renderLogs();",
  "  }",
  "  if (workspaceState.mainTab === 'config' && activeProjectPath) {",
  "    ensureConfigTabDependencies(activeProjectPath);",
  "    void ensureProjectConfig(activeProjectPath);",
  "  }",
  "}",
  "function showProjectRenderFailure(projectPath, source, error) {",
  "  syncWorkspaceLayout();",
  "  renderWorkspaceTabs();",
  "  const el = document.getElementById('mainPanel');",
  "  if (!el) return;",
  "  el.innerHTML =",
  "    '<div class=\"panel-inner\"><div class=\"card\"><div class=\"card-header\"><span>' +",
  "    escHtml(t('mainSelectProject')) +",
  "    '</span></div><div class=\"card-body\"><div class=\"empty-state\" style=\"color:var(--yellow)\">' +",
  "    escHtml(t('projectRenderFailed')) +",
  "    '</div><div class=\"config-help\" style=\"margin-top:8px\">' +",
  "    escHtml(t('projectRenderHint')) +",
  "    '</div><div class=\"config-help\" style=\"margin-top:8px\">' +",
  "    escHtml(projectPath || '—') +",
  "    (source ? ' · ' + escHtml(source) : '') +",
  "    '</div></div></div></div>';",
  "  console.error('[dashboard] main panel render failed', {",
  "    projectPath: projectPath,",
  "    source: source,",
  "    error: String(error),",
  "  });",
  "  enqueueClientError({",
  "    message: 'main panel render failed: ' + String(error),",
  "    source: source || 'renderMainPanel',",
  "    stack: getErrorStack(error),",
  "  });",
  "}",
  "function safeRenderMainPanel(projectPath, source = 'renderMainPanel') {",
  "  try {",
  "    if (typeof captureCurrentSkillDetailDraft === 'function') {",
  "      captureCurrentSkillDetailDraft();",
  "    }",
  "    renderMainPanel(projectPath);",
  "    if (typeof syncCurrentSkillDetailSurface === 'function') {",
  "      syncCurrentSkillDetailSurface();",
  "    }",
  "    return true;",
  "  } catch (error) {",
  "    showProjectRenderFailure(projectPath, source, error);",
  "    return false;",
  "  }",
  "}",
  "async function selectProject(path) {",
  "  state.selectedProjectId = path;",
  "  renderSidebar();",
  "  syncWorkspaceLayout();",
  "  if (!state.projectData[path] && normalizeMainTab(state.selectedMainTab) !== 'skills') {",
  "    document.getElementById('mainPanel').innerHTML = '<div class=\"panel-inner\"><div class=\"no-project\">' + t('mainLoading') + '</div></div>';",
  "  }",
  "  void persistDashboardLanguage(currentLang, path);",
  "  if (!state.projectData[path] || state.staleProjectData[path]) {",
  "    await loadProjectSnapshot(path, { force: !!state.staleProjectData[path] });",
  "  }",
  "  safeRenderMainPanel(path, 'selectProject');",
  "  if (state.providerCatalog.length === 0 && !state.providerCatalogLoading && needsProjectOverviewDependencies()) {",
  "    console.debug('[dashboard] warming provider catalog', { projectPath: path });",
  "    void loadProviderCatalog();",
  "  }",
  "  renderSidebar();",
  "}",
  "function selectMainTab(tab) {",
  "  const workspaceState = syncWorkspaceState(tab);",
  "  syncWorkspaceLayout();",
  "  renderWorkspaceTabs();",
  "  if (workspaceState.mainTab === 'skills') {",
  "    void loadSkillLibrary(false);",
  "  }",
  "  if (needsProjectOverviewDependencies(tab) && state.providerCatalog.length === 0) {",
  "    void loadProviderCatalog(true);",
  "  }",
  "  if (workspaceState.mainTab === 'config' && state.selectedProjectId) {",
  "    ensureConfigTabDependencies(state.selectedProjectId);",
  "  }",
  "  if (workspaceState.mainTab !== 'config' && state.selectedProjectId && state.staleProjectData[state.selectedProjectId]) {",
  "    void loadProjectSnapshot(state.selectedProjectId, { force: true }).then(function() {",
  "      if (state.selectedProjectId) {",
  "        safeRenderMainPanel(state.selectedProjectId, 'selectMainTab:refresh:' + workspaceState.mainTab);",
  "      }",
  "    });",
  "  }",
  "  safeRenderMainPanel(state.selectedProjectId || '', 'selectMainTab:' + workspaceState.mainTab);",
  "  console.debug('[dashboard] switched main tab', {",
  "    tab: workspaceState.mainTab,",
  "    requestedTab: tab,",
  "    skillsSubTab: state.selectedSkillsSubTab,",
  "  });",
  "}",
  "function selectSkillsSubTab(tab) {",
  "  if (tab === 'project_overview') {",
  "    state.selectedSkillsSubTab = 'skill_library';",
  "    selectMainTab('project');",
  "    console.debug('[dashboard] redirected legacy skills sub-tab', { requestedSubTab: tab, targetMainTab: 'project' });",
  "    return;",
  "  }",
  "  state.selectedSkillsSubTab = 'skill_library';",
  "  selectMainTab('skills');",
  "  console.debug('[dashboard] redirected legacy skills sub-tab', { requestedSubTab: tab, targetMainTab: 'skills' });",
  "}",
  "const baseFetchJsonWithTimeout = fetchJsonWithTimeout;",
  "fetchJsonWithTimeout = async function(url, timeoutMs = 8000, options = {}) {",
  "  const data = await baseFetchJsonWithTimeout(url, timeoutMs, options);",
  "  if (String(url) === '/api/logs') {",
  "    state.allLogs = Array.isArray(data && data.lines) ? data.lines : [];",
  "    if (normalizeMainTab(state.selectedMainTab) === 'project') {",
  "      renderLogs();",
  "    }",
  "  }",
  "  return data;",
  "};",
  "const baseSwitchLang = switchLang;",
  "switchLang = async function(lang) {",
  "  await baseSwitchLang(lang);",
  "  syncWorkspaceLayout();",
  "  renderWorkspaceTabs();",
  "  safeRenderMainPanel(state.selectedProjectId || '', 'switchLang');",
  "};",
  "const baseSelectMainTabForBootstrapCache = selectMainTab;",
  "selectMainTab = function(tab) {",
  "  const result = baseSelectMainTabForBootstrapCache(tab);",
  "  scheduleDashboardBootstrapCacheSave('selectMainTab');",
  "  return result;",
  "};",
  "const baseHandleUpdate = handleUpdate;",
  "handleUpdate = async function(data) {",
  "  await baseHandleUpdate(data);",
  "  if (data && Array.isArray(data.changedProjects) && normalizeMainTab(state.selectedMainTab) === 'skills') {",
  "    const preserveInlineSkillLibraryDetail =",
  "      normalizeSkillsSubTab(state.selectedSkillsSubTab) === 'skill_library' &&",
  "      !!state.selectedSkillFamilyId &&",
  "      !!state.currentSkillId;",
  "    if (preserveInlineSkillLibraryDetail) {",
  "      console.debug('[dashboard] refreshing skill library data without reloading active inline skill', {",
  "        familyId: state.selectedSkillFamilyId,",
  "        instanceId: state.currentSkillInstanceId || null,",
  "      });",
  "    }",
  "    await loadSkillLibrary(true, preserveInlineSkillLibraryDetail ? { preserveInlineDetail: true } : undefined);",
  "    if (preserveInlineSkillLibraryDetail) {",
  "      updateSkillsList();",
  "    }",
  "  }",
  "  syncWorkspaceLayout();",
  "  renderWorkspaceTabs();",
  "  if (data && data.logs && normalizeMainTab(state.selectedMainTab) === 'project') {",
  "    renderLogs();",
  "  }",
  "  if (data && (data.projects || data.changedProjects)) {",
  "    scheduleDashboardBootstrapCacheSave('handleUpdate');",
  "  }",
  "};",
  "const baseLoadProviderCatalog = loadProviderCatalog;",
  "loadProviderCatalog = async function(force = false) {",
  "  const activeProjectId = state.selectedProjectId;",
  "  const mainTab = normalizeMainTab(state.selectedMainTab);",
  "  await baseLoadProviderCatalog(force);",
  "  if (activeProjectId && (mainTab === 'config' || mainTab === 'project')) {",
  "    safeRenderMainPanel(activeProjectId, 'loadProviderCatalog:' + mainTab);",
  "  }",
  "};",
  "const baseInit = init;",
  "init = async function() {",
  "  syncWorkspaceState();",
  "  syncWorkspaceLayout();",
  "  renderWorkspaceTabs();",
  "  const bootstrapHydration = hydrateDashboardFromBootstrapCache();",
  "  if (bootstrapHydration && bootstrapHydration.hydrated) {",
  "    renderSidebar();",
  "    safeRenderMainPanel(state.selectedProjectId || '', 'init:bootstrapCache');",
  "  }",
  "  await baseInit();",
  "  syncWorkspaceState();",
  "  syncWorkspaceLayout();",
  "  renderWorkspaceTabs();",
  "  safeRenderMainPanel(state.selectedProjectId || '', 'init');",
  "  scheduleDashboardBootstrapCacheSave('init');",
  "  if (bootstrapHydration && bootstrapHydration.hydrated) {",
  "    void revalidateDashboardBootstrapData();",
  "  }",
  "};",
  "function setActivityLayer(layer) {",
  "  state.activityLayer = layer === 'raw' ? 'raw' : 'business';",
  "  if (state.selectedProjectId) safeRenderMainPanel(state.selectedProjectId, 'setActivityLayer');",
  "}",
  "function setActivityTagFilter(tag) {",
  "  state.activityTagFilter = tag || 'core_flow';",
  "  if (state.selectedProjectId) safeRenderMainPanel(state.selectedProjectId, 'setActivityTagFilter');",
  "}",
].join('\n');

export function renderDashboardMainPanelSource(): string { return DASHBOARD_MAIN_PANEL_SOURCE; }
