/**
 * Bash completion script generator (extracted from completion.ts)
 */

export function generateBashCompletion(): string {
  return [
    '# OrnnSkills Bash Completion',
    '# Source this file: source <(ornn completion bash)',
    '# Or install to: /etc/bash_completion.d/ornn',
    '',
    '_ornn_complete() {',
    '  local cur prev opts',
    '  COMPREPLY=()',
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    '  prev="${COMP_WORDS[COMP_CWORD-1]}"',
    '',
    '  # Main commands',
    '  local commands="init daemon skills logs version help"',
    '  ',
    '  # Skills subcommands',
    '  local skills_commands="status log diff rollback freeze unfreeze sync preview"',
    '  ',
    '  # Daemon subcommands',
    '  local daemon_commands="start stop status"',
    '  ',
    '  # Global options',
    '  local global_opts="--help --version"',
    '',
    '  # Complete based on context',
    '  case "${COMP_WORDS[1]}" in',
    '    skills)',
    '      case "${COMP_WORDS[2]}" in',
    '        status)',
    '          COMPREPLY=( $(compgen -W "--project --skill --help" -- $cur) )',
    '          return 0',
    '          ;;',
    '        log|history)',
    '          COMPREPLY=( $(compgen -W "--project --limit --type --since --until --search --applied-by --help" -- $cur) )',
    '          return 0',
    '          ;;',
    '        diff)',
    '          COMPREPLY=( $(compgen -W "--project --revision --origin --help" -- $cur) )',
    '          return 0',
    '          ;;',
    '        rollback|revert)',
    '          COMPREPLY=( $(compgen -W "--project --to --snapshot --initial --force --help" -- $cur) )',
    '          return 0',
    '          ;;',
    '        freeze)',
    '          COMPREPLY=( $(compgen -W "--project --all --force --dry-run --interactive --help" -- $cur) )',
    '          return 0',
    '          ;;',
    '        unfreeze)',
    '          COMPREPLY=( $(compgen -W "--project --all --force --dry-run --interactive --help" -- $cur) )',
    '          return 0',
    '          ;;',
    '        sync)',
    '          COMPREPLY=( $(compgen -W "--project --force --help" -- $cur) )',
    '          return 0',
    '          ;;',
    '        preview)',
    '          COMPREPLY=( $(compgen -W "--project --revision --help" -- $cur) )',
    '          return 0',
    '          ;;',
    '        *)',
    '          if [[ $cur == -* ]]; then',
    '            COMPREPLY=( $(compgen -W "--help" -- $cur) )',
    '          else',
    '            COMPREPLY=( $(compgen -W "$skills_commands" -- $cur) )',
    '          fi',
    '          return 0',
    '          ;;',
    '      esac',
    '      ;;',
    '    daemon)',
    '      case "${COMP_WORDS[2]}" in',
    '        start|stop|status)',
    '          COMPREPLY=( $(compgen -W "--project --help" -- $cur) )',
    '          return 0',
    '          ;;',
    '        *)',
    '          if [[ $cur == -* ]]; then',
    '            COMPREPLY=( $(compgen -W "--help" -- $cur) )',
    '          else',
    '            COMPREPLY=( $(compgen -W "$daemon_commands" -- $cur) )',
    '          fi',
    '          return 0',
    '          ;;',
    '      esac',
    '      ;;',
    '    logs)',
    '      COMPREPLY=( $(compgen -W "--project --tail --level --skill --follow --help" -- $cur) )',
    '      return 0',
    '      ;;',
    '    init)',
    '      COMPREPLY=( $(compgen -W "--force --help" -- $cur) )',
    '      return 0',
    '      ;;',
    '    *)',
    '      if [[ $cur == -* ]]; then',
    '        COMPREPLY=( $(compgen -W "$global_opts" -- $cur) )',
    '      else',
    '        COMPREPLY=( $(compgen -W "$commands" -- $cur) )',
    '      fi',
    '      return 0',
    '      ;;',
    '  esac',
    '}',
    '',
    'complete -F _ornn_complete ornn',
    '',
  ].join('\n');
}
