/**
 * Fish completion script generator (extracted from completion.ts)
 */

export function generateFishCompletion(): string {
  return [
    '# OrnnSkills Fish Completion',
    '# Install to: ~/.config/fish/completions/ornn.fish',
    '',
    '# Main commands',
    'complete -c ornn -f',
    "complete -c ornn -n '__fish_use_subcommand' -a 'init' -d 'Initialize Ornn Skills in current project'",
    "complete -c ornn -n '__fish_use_subcommand' -a 'daemon' -d 'Manage the OrnnSkills background daemon'",
    "complete -c ornn -n '__fish_use_subcommand' -a 'skills' -d 'Manage shadow skills'",
    "complete -c ornn -n '__fish_use_subcommand' -a 'logs' -d 'View OrnnSkills logs'",
    "complete -c ornn -n '__fish_use_subcommand' -a 'completion' -d 'Generate shell completion scripts'",
    '',
    '# Global options',
    "complete -c ornn -s h -l help -d 'Show help'",
    "complete -c ornn -s v -l version -d 'Show version'",
    '',
    '# Init options',
    "complete -c ornn -n '__fish_seen_subcommand_from init' -l force -d 'Force reinitialization'",
    '',
    '# Daemon subcommands',
    "complete -c ornn -n '__fish_seen_subcommand_from daemon' -a 'start' -d 'Start the daemon'",
    "complete -c ornn -n '__fish_seen_subcommand_from daemon' -a 'stop' -d 'Stop the daemon'",
    "complete -c ornn -n '__fish_seen_subcommand_from daemon' -a 'status' -d 'Check daemon status'",
    '',
    '# Daemon options',
    "complete -c ornn -n '__fish_seen_subcommand_from daemon' -s p -l project -d 'Project root path' -a '(__fish_complete_directories)'",
    '',
    '# Skills subcommands',
    "complete -c ornn -n '__fish_seen_subcommand_from skills' -a 'status' -d 'Show status of shadow skills'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills' -a 'log' -d 'Show evolution log'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills' -a 'diff' -d 'Show diff with origin'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills' -a 'rollback' -d 'Rollback to previous version'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills' -a 'freeze' -d 'Pause automatic optimization'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills' -a 'unfreeze' -d 'Resume automatic optimization'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills' -a 'sync' -d 'Sync to origin'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills' -a 'preview' -d 'Preview changes'",
    '',
    '# Skills status options',
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from status' -s p -l project -d 'Project root path' -a '(__fish_complete_directories)'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from status' -s s -l skill -d 'Show detailed status for specific skill'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from status' -s i -l interactive -d 'Select skill interactively'",
    '',
    '# Skills log options',
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from log' -s p -l project -d 'Project root path' -a '(__fish_complete_directories)'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from log' -s n -l limit -d 'Number of records'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from log' -s t -l type -d 'Filter by change type' -a 'append_context tighten_trigger add_fallback prune_noise rewrite_section'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from log' -l since -d 'Show records since date'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from log' -l until -d 'Show records until date'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from log' -l search -d 'Search in reason field'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from log' -l applied-by -d 'Filter by source' -a 'auto manual'",
    '',
    '# Skills diff options',
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from diff' -s p -l project -d 'Project root path' -a '(__fish_complete_directories)'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from diff' -s r -l revision -d 'Compare with specific revision'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from diff' -s o -l origin -d 'Compare with origin skill'",
    '',
    '# Skills rollback options',
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from rollback' -s p -l project -d 'Project root path' -a '(__fish_complete_directories)'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from rollback' -s t -l to -d 'Rollback to specific revision'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from rollback' -s s -l snapshot -d 'Rollback to latest snapshot'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from rollback' -s i -l initial -d 'Rollback to initial version'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from rollback' -s f -l force -d 'Skip confirmation prompt'",
    '',
    '# Skills freeze/unfreeze options',
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from freeze' -s p -l project -d 'Project root path' -a '(__fish_complete_directories)'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from freeze' -l all -d 'Freeze all skills'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from freeze' -s f -l force -d 'Skip confirmation prompt'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from freeze' -l dry-run -d 'Show what would be frozen without making changes'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from freeze' -s i -l interactive -d 'Select skills interactively'",
    '',
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from unfreeze' -s p -l project -d 'Project root path' -a '(__fish_complete_directories)'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from unfreeze' -l all -d 'Unfreeze all skills'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from unfreeze' -s f -l force -d 'Skip confirmation prompt'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from unfreeze' -l dry-run -d 'Show what would be unfrozen without making changes'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from unfreeze' -s i -l interactive -d 'Select skills interactively'",
    '',
    '# Skills sync options',
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from sync' -s p -l project -d 'Project root path' -a '(__fish_complete_directories)'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from sync' -s f -l force -d 'Force sync without confirmation'",
    '',
    '# Skills preview options',
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from preview' -s p -l project -d 'Project root path' -a '(__fish_complete_directories)'",
    "complete -c ornn -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from preview' -s r -l revision -d 'Preview changes from specific revision'",
    '',
    '# Logs options',
    "complete -c ornn -n '__fish_seen_subcommand_from logs' -s p -l project -d 'Project root path' -a '(__fish_complete_directories)'",
    "complete -c ornn -n '__fish_seen_subcommand_from logs' -s n -l tail -d 'Number of lines to show'",
    "complete -c ornn -n '__fish_seen_subcommand_from logs' -s l -l level -d 'Filter by level' -a 'error warn info debug'",
    "complete -c ornn -n '__fish_seen_subcommand_from logs' -s s -l skill -d 'Filter logs for specific skill'",
    "complete -c ornn -n '__fish_seen_subcommand_from logs' -s f -l follow -d 'Follow log output'",
    '',
    '# Completion options',
    "complete -c ornn -n '__fish_seen_subcommand_from completion' -a 'bash' -d 'Generate bash completion'",
    "complete -c ornn -n '__fish_seen_subcommand_from completion' -a 'zsh' -d 'Generate zsh completion'",
    "complete -c ornn -n '__fish_seen_subcommand_from completion' -a 'fish' -d 'Generate fish completion'",
    "complete -c ornn -n '__fish_seen_subcommand_from completion' -s o -l output -d 'Output file path'",
    '',
  ].join('\n');
}
