/**
 * Zsh completion script generator (extracted from completion.ts)
 */

export function generateZshCompletion(): string {
  return [
    '#compdef ornn',
    '',
    '# OrnnSkills Zsh Completion',
    '# Install to: /usr/share/zsh/site-functions/_ornn',
    '# Or add to fpath: fpath+=(~/.zsh/completions)',
    '',
    '_ornn() {',
    '  local curcontext="$curcontext" state line',
    '  typeset -A opt_args',
    '',
    '  _arguments -C \\',
    "    '(-h --help)'{-h,--help}'[Show help]' \\",
    "    '(-v --version)'{-v,--version}'[Show version]' \\",
    "    '1: :_ornn_commands' \\",
    "    '*:: :->args'",
    '',
    '  case "$line[1]" in',
    '    skills)',
    '      _ornn_skills',
    '      ;;',
    '    daemon)',
    '      _ornn_daemon',
    '      ;;',
    '    logs)',
    '      _arguments \\',
    "        '(-p --project)'{-p,--project}'[Project root path]:path:_directories' \\",
    "        '(-n --tail)'{-n,--tail}'[Number of lines]:number:' \\",
    "        '(-l --level)'{-l,--level}'[Filter by level]:level:(error warn info debug)' \\",
    "        '(-s --skill)'{-s,--skill}'[Filter by skill]:skill:_ornn_skill_ids' \\",
    "        '(-f --follow)'{-f,--follow}'[Follow log output]'",
    '      ;;',
    '    init)',
    '      _arguments \\',
    "        '--force[Force reinitialization]'",
    '      ;;',
    '  esac',
    '}',
    '',
    '_ornn_commands() {',
    '  local commands=(',
    "    'init:Initialize Ornn Skills in current project'",
    "    'daemon:Manage the OrnnSkills background daemon'",
    "    'skills:Manage shadow skills'",
    "    'logs:View OrnnSkills logs'",
    "    'completion:Generate shell completion scripts'",
    '  )',
    "  _describe -t commands 'ornn commands' commands",
    '}',
    '',
    '_ornn_skills() {',
    '  local curcontext="$curcontext"',
    '  ',
    '  if (( CURRENT == 1 )); then',
    '    local subcommands=(',
    "      'status:Show status of shadow skills'",
    "      'log:Show evolution log for a shadow skill'",
    "      'diff:Show diff between shadow skill and origin'",
    "      'rollback:Rollback a shadow skill to a previous version'",
    "      'freeze:Pause automatic optimization for a shadow skill'",
    "      'unfreeze:Resume automatic optimization for a shadow skill'",
    "      'sync:Sync shadow skill back to origin'",
    "      'preview:Preview changes that would be applied'",
    '    )',
    "    _describe -t commands 'skills subcommands' subcommands",
    '  else',
    '    shift words',
    '    (( CURRENT-- ))',
    '    ',
    '    case "$line[1]" in',
    '      status)',
    '        _arguments \\',
    "          '(-p --project)'{-p,--project}'[Project root path]:path:_directories' \\",
    "          '(-s --skill)'{-s,--skill}'[Show detailed status for specific skill]:skill:_ornn_skill_ids' \\",
    "          '(-i --interactive)'{-i,--interactive}'[Select skill interactively]'",
    '        ;;',
    '      log|history)',
    '        _arguments \\',
    "          '(-p --project)'{-p,--project}'[Project root path]:path:_directories' \\",
    "          '(-n --limit)'{-n,--limit}'[Number of records]:number:' \\",
    "          '(-t --type)'{-t,--type}'[Filter by change type]:type:(append_context tighten_trigger add_fallback prune_noise rewrite_section)' \\",
    "          '--since[Show records since date]:date:' \\",
    "          '--until[Show records until date]:date:' \\",
    "          '--search[Search in reason field]:keyword:' \\",
    "          '--applied-by[Filter by source]:source:(auto manual)' \\",
    "          ':skill:_ornn_skill_ids'",
    '        ;;',
    '      diff)',
    '        _arguments \\',
    "          '(-p --project)'{-p,--project}'[Project root path]:path:_directories' \\",
    "          '(-r --revision)'{-r,--revision}'[Compare with specific revision]:revision:' \\",
    "          '(-o --origin)'{-o,--origin}'[Compare with origin skill]' \\",
    "          ':skill:_ornn_skill_ids'",
    '        ;;',
    '      rollback|revert)',
    '        _arguments \\',
    "          '(-p --project)'{-p,--project}'[Project root path]:path:_directories' \\",
    "          '(-t --to)'{-t,--to}'[Rollback to specific revision]:revision:' \\",
    "          '(-s --snapshot)'{-s,--snapshot}'[Rollback to latest snapshot]' \\",
    "          '(-i --initial)'{-i,--initial}'[Rollback to initial version]' \\",
    "          '(-f --force)'{-f,--force}'[Skip confirmation prompt]' \\",
    "          ':skill:_ornn_skill_ids'",
    '        ;;',
    '      freeze)',
    '        _arguments \\',
    "          '(-p --project)'{-p,--project}'[Project root path]:path:_directories' \\",
    "          '--all[Freeze all skills]' \\",
    "          '(-f --force)'{-f,--force}'[Skip confirmation prompt]' \\",
    "          '--dry-run[Show what would be frozen without making changes]' \\",
    "          '(-i --interactive)'{-i,--interactive}'[Select skills interactively]' \\",
    "          ':skill:_ornn_skill_ids'",
    '        ;;',
    '      unfreeze)',
    '        _arguments \\',
    "          '(-p --project)'{-p,--project}'[Project root path]:path:_directories' \\",
    "          '--all[Unfreeze all skills]' \\",
    "          '(-f --force)'{-f,--force}'[Skip confirmation prompt]' \\",
    "          '--dry-run[Show what would be unfrozen without making changes]' \\",
    "          '(-i --interactive)'{-i,--interactive}'[Select skills interactively]' \\",
    "          ':skill:_ornn_skill_ids'",
    '        ;;',
    '      sync)',
    '        _arguments \\',
    "          '(-p --project)'{-p,--project}'[Project root path]:path:_directories' \\",
    "          '(-f --force)'{-f,--force}'[Force sync without confirmation]' \\",
    "          ':skill:_ornn_skill_ids'",
    '        ;;',
    '      preview)',
    '        _arguments \\',
    "          '(-p --project)'{-p,--project}'[Project root path]:path:_directories' \\",
    "          '(-r --revision)'{-r,--revision}'[Preview changes from specific revision]:revision:' \\",
    "          ':skill:_ornn_skill_ids'",
    '        ;;',
    '    esac',
    '  fi',
    '}',
    '',
    '_ornn_daemon() {',
    '  if (( CURRENT == 1 )); then',
    '    local subcommands=(',
    "      'start:Start the OrnnSkills daemon'",
    "      'stop:Stop the OrnnSkills daemon'",
    "      'status:Check daemon status'",
    '    )',
    "    _describe -t commands 'daemon subcommands' subcommands",
    '  else',
    '    _arguments \\',
    "      '(-p --project)'{-p,--project}'[Project root path]:path:_directories'",
    '  fi',
    '}',
    '',
    '_ornn_skill_ids() {',
    '  # Try to get skill IDs from the current project',
    '  local skills=()',
    '  if [[ -d .ornn/skills ]]; then',
    '    for dir in .ornn/skills/*(/); do',
    '      if [[ -d "$dir" ]]; then',
    '        skills+=("$(basename "$dir")")',
    '      fi',
    '    done',
    '  fi',
    '  ',
    '  if (( ${#skills} > 0 )); then',
    "    _describe -t skills 'skill IDs' skills",
    '  else',
    "    _message 'skill ID'",
    '  fi',
    '}',
    '',
    '_ornn "$@"',
    '',
  ].join('\n');
}
